// 389. Find the Difference

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

let findTheDifference = function (shortString, longString) {
  for (let i = 0; i < longString.length; i++) {
    let find = false;

    for (let j = 0; j < shortString.length; j++) {
      if (longString[i] === shortString[j]) {
        find = true;

        break;
      }
    }

    if (!find) {
      return longString[i];
    }
  }

  return "";
};

let longString = "abcde";
let shortString = "abcd";

let result = findTheDifference(shortString, longString);

console.log(result);
